---
# tasks file for openjdk-ansible
#

- name: judge JAVA_HOME exists
  #  shell: echo $JAVA_HOME
  shell: which jps
  register: java_home 

- debug: msg={{ java_home }}

- block:

    - name: install openjdk 
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - 'java-1.8.0-openjdk'
        - 'java-1.8.0-openjdk-devel'
      when:  ansible_os_family == "RedHat" 

    - name: get jdk home 
      shell: dirname `readlink -f \`which java\``
      register: java_path

    - debug: msg={{ java_path  }}
 
    - name: JAVA_HOME is in PATH?
      shell: grep JAVA_HOME ~/.bashrc
      register: isExist

    - name: set jdk home
      shell:  path=`dirname \`dirname {{ java_path.stdout }}\`` ; \
          echo "export JAVA_HOME=$path" >> ~/.bashrc; \
          echo 'export PATH=$PATH:$JAVA_HOME/bin' >> ~/.bashrc ;
          source ~/.bashrc
      when: isExist.rc != 0

  #  when: not  java_home.stdout.find("java")
  when: java_home.rc == 0
  



