---

- name: install openjdk
  package: name={{ item }}  state=present
  with_items:
    - 'java-{{ java_version }}-openjdk' 
    - 'java-{{ java_version }}-openjdk-devel'
  tags: 
    - env 
    - jdk 

- name: create ~/bigdata/spark directory
  file:
    dest: ~/bigdata/spark/
    state: directory 
  tags: 
    - spark 
    - config 

- name: create /var/bigdata/spark directory
  file:
    dest: /var/bigdata/
    state: directory
  tags: 
    - spark 
    - config 

- name: create /var/bigdata/scala  directory
  file:
    dest: /var/bigdata/ 
    state: directory
  tags: 
    - spark 
    - env 

- name: copy scala file to all targets
  copy: 
    src:  ~/bigdata/spark/scala-{{ scala_version }}.tgz 
    dest: ~/bigdata/spark/scala-{{ scala_version }}.tgz 
  tags: 
    - spark 
    - env 

- name: copy spark file to all targets
  copy:
    src: ~/bigdata/spark/spark-{{ spark_version }}-bin-hadoop2.7.tgz 
    dest: ~/bigdata/spark/spark-{{ spark_version }}-bin-hadoop2.7.tgz 
  tags: 
      - spark 
      - config 

- name: unarchive spark package
  unarchive:
    src: ~/bigdata/spark/spark-{{ spark_version }}-bin-hadoop2.7.tgz 
    dest: ~/bigdata/spark/ 
    creates: ~/bigdata/spark/spark-{{ spark_version }}-bin-hadoop2.7/src/spark/README.md
    remote_src: yes 
  tags: 
    - spark 
    - config 

- name: change spark name
  file:
    src: ~/bigdata/spark/spark-{{ spark_version }}-bin-hadoop2.7 
    dest: /var/bigdata/spark
    state: link
    force: yes 
  tags: 
    - spark
    - config 


- name: unarchive scala package
  unarchive:
    src: ~/bigdata/spark/scala-{{ scala_version }}.tgz 
    dest: ~/bigdata/spark/  
    remote_src: yes
  tags:
    - spark
    - config 


- name: change scala name 
  file:
    src: ~/bigdata/spark/scala-{{ scala_version }}
    dest: /var/bigdata/scala
    state: link 
    force: yes
  tags: spark

- name: copy sparkRunningEnv.sh file 
  copy:
    src: sparkRunningEnv.sh
    dest: ~/bigdata/spark/ 
    mode: u+x
  tags: spark

- name: setup spark run envariment
  command: ~/bigdata/spark/sparkRunningEnv.sh all 
  tags: spark


- name: copy hosts file 
  template:
    src: hosts.template 
    dest: /etc/hosts  
    backup: yes 
  tags: spark 

- name: copy spark config file
  template: src={{ item.name }} dest=/var/bigdata/spark/conf/  mode={{ item.mode }}
  with_items:
    - { name: 'slaves' , mode: '0600' }
    - { name: 'spark-env.sh' , mode: '0700' }
  tags: spark


