metadata:
    name: grafana
    format: "Lava-Test-Shell Test Definition 1.0"
    description: "grafana 可视化的工具."
    maintainer:
        - shuangchengchen@qq.com
        - fyuanz_2010@163.com
    os:
        - centos
    scope:
        - tool
    devices:
        - d03
        - d05
    level: 5

params:
    # Test if lshw able to report the classes pre-defined in ${CLASSES}.
    SKIP_INSTALL: "false"

run:
    steps:
        - cd ./auto-test/middleware/tool/grafana
        - ./grafana.sh -s "${SKIP_INSTALL}" 
        - cd -
parse:
    pattern: "^(?!.+ED)(?P<test_case_id>\\w+)\\s+(?P<result>\\w+)\\s+\\d$"
    fixupdict:
        FAIL: fail
        PASS: pass
