metadata:
    name: grafana
    format: "Lava-Test-Shell Test Definition 1.0"
    description: "grafana 可视化的工具."
    maintainer:
        - 1136920311@qq.com
    os:
        - centos
    scope:
        - tool
    devices:
        - d03
        - d05
    level: 1
    totalcase:
        centos: 6

run:
    steps:
        - "cd auto-test/middleware/tool/grafana; ./grafana.sh; cd -"
parse:
    pattern: "^(?!.+ED)(?P<test_case_id>\\w+)\\s+(?P<result>\\w+)\\s+\\d$"
    fixupdict:
        FAIL: fail
        PASS: pass
