
metadata:
    name: workload-testing
    format: "Lava-Test-Shell Test Definition 1.0"
    description: "workload is a simple HTTP performance testing tool"
    maintainer:
        - hongxin_228@163.com
    scope:
        - distribution
    os:
        - centos
    devices:
        - d05
        - d03
    level: 5
    totalcase: 16
run:
    steps:
        - "cd auto-test/distributions/distribution/workload-automation; ./workload-automation.sh; cd - "
parse:
   pattern: "^(?!.+ED)(?P<test_case_id>\\w+)\\s+(?P<result>\\w+)\\s+\\d$"
   fixupdict:
   FAIL: fail
   PASS: pass
